services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    ports:
      - 8384:8384        # GUI
      - 22000:22000/tcp  # Sync
      - 22000:22000/udp
      - 21027:21027/udp  # LAN discovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Dakar
    volumes:
      - /home/uriel/Partage:/var/syncthing/data       # ðŸ”‘ donnÃ©es
      - /home/uriel/syncthing-config:/var/syncthing/config  # ðŸ”‘ config
    restart: unless-stopped

